name: Publish to npm

on:
  workflow_dispatch:
  release:
      types: [released]
      
jobs:
  publish:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test  # Modifique conforme a necessidade para rodar os testes

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Publicação da versão ${{ github.ref_name }} no npm.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
